### PR TITLE
Add UI support for user-guided schema conversion

### LINKED ISSUE #22: Support user-guided schema conversion
Currently we fully automate schema conversion.

However, many aspects of schema conversion represent choices. We should provide a way for users to provide input to control these choices. Some options to consider:
a) allow a user to edit the schema we build and feed it back as input to HarbourBridge
b) provide a preference configuration for common translations e.g. numeric
c) provide a UI that presents choices and advice for each choice, prioritized by an estimate of the importance of each choice

### PR DESCRIPTION
**Pull request by amar-appdev**
Fixes #22 

- Verified that the unit tests for components written using jest pass
- Verified that the end-to-end integration tests written using puppeteer pass
- Verified that the tests run as part of .circle CI pipeline to catch any regressions
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by jereneyz — APPROVED** [review]
LGTM

**Comment by amar-appdev** [comment]
@googlebot I signed it!

**Comment by amar-appdev** [comment]
@googlebot I fixed it.

**Comment by amar-appdev** [comment]
@googlebot I fixed it.

**Comment by amar-appdev** [comment]
@googlebot I signed it!

**Comment by amar-appdev** [comment]
@googlebot I fixed it.

**Comment by agasheesh** [comment]
Manually verified that the CLAs look good. The author `amar-appdev` for these changes had successfully signed the CLA agreement as well as commented saying that `@googlebot I fixed it.`. At that time, the cla was approved by the bot.

But after the same author recommitted the changes to also reflect their full name `Amarnath Bagineni` instead of showing `amar-appdev`, it tripped the bot in thinking that it's some different user.

We had to remove manually add the label `cla:yes` to get around this problem.

**Review by nevinheintze — APPROVED** [review]
Approving PR.
Please sync with Asheesh and wait for his approval for submitting.

**Review by agasheesh — APPROVED** [review]
Thanks for all the work here! LGTM.

**Pull request merged**
