### PR TITLE
fix: update to exit early when the file is not parsable.

### PR DESCRIPTION
**Pull request by hengfengli**
This is a revert for #44. The new added test is broken due to the last change, which has been fixed.

### CODE REVIEW

**Comment by hengfengli** [comment]
@nevinheintze We should configure running unit tests in PR checks. PR must pass unit tests before merging. 

Sorry for the inconvenience. I saw a `green` "squash and merge" button soI thought the unit tests are passed.

**Comment by lgruen** [comment]
Good idea, but we'd need to find a way to trigger the "ci/circleci:
build_and_test" check before the merge, but after approval. We don't want
to run it for any PR as that would risk leaking credentials.

**Comment by hengfengli** [comment]
@lgruen I think we can have two CircleCi jobs, i.e., unit tests and integration tests (or builds). We only run unit tests for forked PRs (a PR from a forked repo). When you enable CI for forked PRs, it should provide an option “Pass secrets to builds from forked pull requests”, which is disabled by default. So the environment variables are not visible in the unit tests in forked PRs. 

When the forked PR is approved and merged with the master, this becomes a push to the master repo (not a forked PR) so it will trigger both unit tests and integration tests and the secrets will be visible to them. 

Please see the example in the reference. 

### Reference
* https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/

**Comment by hengfengli** [comment]
I set up a small demo: https://github.com/hengfengli/test-circleci. It works well.

**Pull request merged**
